version: '3'
services:

  postgres-db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: dev_admin
      POSTGRES_DB: olympus
    networks:
      - leapx

networks:
  leapx:
    driver: bridge
