version: '3'
services:
  
  postgres-db:
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - '../../../${ENV:-dev}.env'
      - ../../../docker-secrets/db.env
    networks:
      - leapx


networks:
  leapx:
    driver: bridge
